config:
  variables:
    GIT-CHANGES: ""
    GIT-BRANCH: ""
    GIT-URL: ""

task:
  
  - id: check-have-changes
    options:
      invisible: true    
    script:
      - "#@var GIT-CHANGES git status -s"
      - "#@var GIT-STASH git stash list"      
       
  - id: check-git-url
    options:
      invisible: true    
    script:      
      - "#@var GIT-URL git config --get remote.origin.url"

  - id: check-git-branch
    options:
      invisible: true    
    script:      
      - "#@var GIT-BRANCH git rev-parse --abbrev-ref HEAD"      

  #### show infos we have ############ 
  - id: git-status
    needs:
      - check-have-changes
      - check-git-url
      - check-git-branch

  - id: git-status
    require:
      variables:
         GIT-BRANCH: "*"
    script:
       - echo "GIT BRANCH [${GIT-BRANCH}]"

  - id: git-status
    require:
      variables:
         GIT-URL: "*"
    script:
       - echo "GIT REPO   [${GIT-URL}]"


  - id: git-status
    require:
      variables:
        GIT-CHANGES: "!"
    script:
      - echo "no local changes found" 

  - id: git-status
    require:
      variables:
        GIT-CHANGES: "*"
    script:
      - echo "found local changes"
      - echo "------------------"
      - echo "${GIT-CHANGES}"
   
  #### pull changes #################
  - id: git-pull
    needs:
      - check-have-changes
      
  - id: git-pull
    script:
      - echo " ---- changes"
      - echo "${GIT-CHANGES}"    
      - echo " ---- stash"
      - echo "${GIT-STASH}"

  - id: git-pull
    require:
      variables:
        GIT-CHANGES: ""
    script:
      - git pull --rebase

  - id: git-pull
    require:
      variables:
        GIT-CHANGES: "*"
        GIT-STASH: ""
    script:
      - echo "stash changes first"
      - git stash
      - git pull --rebase
      - git stash pop

  - id: git-pull
    require:
      variables:
        GIT-STASH: "*"
    script:
      - echo " --- stash exists already."
      - echo " --- you need to clean the stash before. if you are sure this is not needed anymore"
      - git stash show    
      - echo "for removal of the stash use git stash drop"
      
